version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
      - "5672:5672"   # RabbitMQ의 기본 포트
      - "15672:15672" # RabbitMQ 관리 UI 포트
      - "61613:61613" # STOMP over TCP
      - "15674:15674" # WebSocket용 STOMP

    volumes:
      - ./data/rabbitmq:/var/lib/rabbitmq # RabbitMQ 데이터 디렉토리
      - ./rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf # RabbitMQ 설정 파일
      -
    networks:
      - mynetwork

  app:
    image: ${DOCKERHUB_USERNAME}/${DOCKER_IMAGE_TAG_NAME}:latest
    container_name: app
    ports:
      - "8080:8080" # 애플리케이션 포트
    env_file:
      - .env # .env 파일에서 환경 변수를 가져옵니다
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
