version: '3'
services:
  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5672:5672"   # AMQP port
      - "15672:15672" # Management UI port
      - "61613:61613" # STOMP port
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    command: >
      sh -c "rabbitmq-plugins enable rabbitmq_stomp rabbitmq_management;
             rabbitmq-server"
