spring:
  application:
    name: TeamSsc

    mail:
      password: ${EMAIL_PASSWORD}
      username: ${EMAIL_USERNAME}
      properties:
        mail:
          smtp:
            auth: true
            starttls:
              enable: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 5MB
      max-request-size: 10MB

  datasource:
#    url: jdbc:mysql://localhost:3306/teamSSC
#    url: jdbc:mysql://3.38.181.152:3306/teamSSC
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true

#  rabbitmq:
#    host: localhost
#    username: guest
#    password: guest
#    port: 5672

#  rabbitmq:
#    host: ${RABBITMQ_HOST}
#    username: ${RABBITMQ_USERNAME}
#    password: ${RABBITMQ_PASSWORD}
#    port: ${RABBITMQ_PORT}


jwt:
  secret:
    key: ${JWT_SECRET_KEY}
  token:
    expiration: 1800000
  refresh:
    token:
      expiration: 1209600000
server:
  port: 8080

#fcm:
#  firebase_config_path: firebase-service-account.json

fcm:
  firebase_project_id: ${FIREBASE_PROJECT_ID}
  firebase_private_key_id: ${FIREBASE_PRIVATE_KEY_ID}
  firebase_private_key: ${FIREBASE_PRIVATE_KEY}
  firebase_client_email: ${FIREBASE_CLIENT_EMAIL}
  firebase_client_id: ${FIREBASE_CLIENT_ID}
  firebase_auth_uri: ${FIREBASE_AUTH_URI}
  firebase_token_uri: ${FIREBASE_TOKEN_URI}
  firebase_auth_provider_cert_url: ${FIREBASE_AUTH_PROVIDER_CERT_URL}
  firebase_client_cert_url: ${FIREBASE_CLIENT_CERT_URL}
  firebase_universe_domain: ${FIREBASE_UNIVERSE_DOMAIN}


logging:
  level:
    org.springframework.messaging: DEBUG
    org.springframework.amqp: DEBUG
    org.springframework.web.socket: DEBUG
    com.sparta.teamssc: DEBUG


slack:
  webhook:
    url: ${SLACK_WEBHOOK_URL}

secret:
  admin-key: ${ADMIN_SECRET_KEY}
