spring:
  application:
    name: TeamSsc

    mail:
      password: ${EMAIL_PASSWORD}
      username: ${EMAIL_USERNAME}
      properties:
        mail:
          smtp:
            auth: true
            starttls:
              enable: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 100MB

  datasource:
#    url: jdbc:mysql://localhost:3306/teamSSC
#    url: jdbc:mysql://52.78.187.71:3306/teamSSC
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true



fcm:
  project-id: ${FCM_PROJECT_ID}
  private-key-id: ${FCM_PRIVATE_KEY_ID}
  private-key: ${FCM_PRIVATE_KEY}
  client-email: ${FCM_CLIENT_EMAIL}
  client-id: ${FCM_CLIENT_ID}
  auth-uri: ${FCM_AUTH_URI}
  token-uri: ${FCM_TOKEN_URI}
  auth-provider-x509-cert-url: ${FCM_AUTH_PROVIDER_X509_CERT_URL}
  client-x509-cert-url: ${FCM_CLIENT_X509_CERT_URL}
  universe-domain: ${FCM_UNIVERSE_DOMAIN}

jwt:
  secret:
    key: ${JWT_SECRET_KEY}
  token:
    expiration: 1800000
  refresh:
    token:
      expiration: 1209600000
server:
  port: 8080


logging:
  level:
    org.springframework.messaging: DEBUG
    org.springframework.amqp: DEBUG
    org.springframework.web.socket: DEBUG
    com.sparta.teamssc: DEBUG


slack:
  webhook:
    url: ${SLACK_WEBHOOK_URL}

secret:
  admin-key: ${ADMIN_SECRET_KEY}
