spring:
  application:
    name: TeamSsc

    mail:
      password: ${EMAIL_PASSWORD}
      username: ${EMAIL_USERNAME}
      properties:
        mail:
          smtp:
            auth: true
            starttls:
              enable: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 5MB
      max-request-size: 10MB

  datasource:
#    url: jdbc:mysql://localhost:3306/teamSSC
#    url: jdbc:mysql://43.202.54.250:3306/teamSSC
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
      database-platform: org.hibernate.dialect.MySQLDialect

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
jwt:
  secret:
    key: ${JWT_SECRET_KEY}
  token:
    expiration: 1800000
  refresh:
    token:
      expiration: 1209600000
server:
  port: 8080

fcm:
  firebase_config_path: firebase-service-account.json

logging:
  level:
    org.springframework: DEBUG

secret:
  admin-key: ${ADMIN_SECRET_KEY}