spring:
  application:
    name: TeamSsc

    mail:
      password: fprmzufswvwwtchz
      username: teamssc2@gmail.com
      properties:
        mail:
          smtp:
            auth: true
            starttls:
              enable: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 5MB
      max-request-size: 10MB

  datasource:
    url: jdbc:mysql://localhost:3306/teamSSC
#    url: jdbc:mysql://3.38.181.152:3306/teamSSC
#    url: ${DB_URL}
    username: dami
    password: asdf1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
jwt:
  secret:
    key: 7Iqk7YyM66W07YOA7L2U65Sp7YG065+9U3ByaW5n6rCV7J2Y7Yqc7YSw7LWc7JuQ67mI7J6F64uI64ukLg==
  token:
    expiration: 1800000
  refresh:
    token:
      expiration: 1209600000
server:
  port: 8080

fcm:
  firebase_config_path: firebase-service-account.json

logging:
  level:
    org.springframework: DEBUG

secret:
  admin-key: AAABnvxRVklrnYxKZ0aHgTBcXukeZygoC

